const translations = {
    "bg": {
        "nav-home": "Начало",
        "nav-routes": "Маршрути",
        "nav-schedule": "Разписание",
        "nav-fleet": "Автопарк",
        "nav-contact": "Контакти",
        "btn-book": "Резервирай",
        "footer-text": "&copy; 2024 EuroTrans. Всички права запазени.",

        // Начало
        "hero-title": "Комфортно пътуване: България <-> Молдова",
        "hero-desc": "Лукс, Wi-Fi и професионално обслужване.",
        "hero-btn": "Запази място",
        "why-title": "Защо да изберете нас?",
        "card-1-title": "Без скрити такси",
        "card-1-desc": "Крайна цена с включен багаж.",
        "card-2-title": "Удобство",
        "card-2-desc": "Спираме за почивка на удобни места.",
        "card-3-title": "VIP Пътуване",
        "card-3-desc": "Пътувайте със стил с нашите нови автомобили.",

        // Маршрути
        "routes-title": "Нашите Маршрути",
        "route-1-title": "Линия: България - Молдова",
        "route-1-path": "София ➔ Русе ➔ Галац ➔ Кишинев",
        "route-1-info": "Транзит през: Румъния (Дунав мост, Букурещ околовръстно, Галац).",
        "route-2-title": "Линия: Молдова - България",
        "route-2-path": "Кишинев ➔ Галац ➔ Русе ➔ София",
        "route-2-info": "Обратен курс по същия маршрут.",

        // Разписание
        "schedule-title": "Седмично Разписание",
        "th-day": "Ден",
        "th-dest": "Направление",
        "th-time": "Час на тръгване",
        "th-type": "Автомобил",
        "sched-row-1-day": "Петък",
        "sched-row-1-dest": "София -> Кишинев",
        "sched-row-2-day": "Неделя",
        "sched-row-2-dest": "Кишинев -> София",
        "sched-note": "* Пристигането зависи от преминаването на границите.",

        // Автопарк
        "fleet-title": "Нашите Автомобили",
        "fleet-1-title": "Mercedes-Benz V-Class",
        "fleet-1-desc": "Истински VIP комфорт. Кожени седалки, индивидуални масички и климатроник за всеки пътник.",
        "fleet-2-title": "Mercedes Sprinter VIP",
        "fleet-2-desc": "Просторен микробус за малки групи с голям багажник и телевизия.",

        // Контакти
        "contact-title": "Свържете се с нас",
        "office-title": "Офис",
        "work-hours": "Работно време",
        "form-title": "Онлайн Резервация",
        "lbl-name": "Име:",
        "lbl-phone": "Телефон:",
        "lbl-route": "Маршрут:",
        "lbl-date": "Дата:",
        "lbl-info": "Инфо:",
        "btn-send": "Изпрати"
    },
    "en": {
        "nav-home": "Home",
        "nav-routes": "Routes",
        "nav-schedule": "Schedule",
        "nav-fleet": "Fleet",
        "nav-contact": "Contact",
        "btn-book": "Book Now",
        "footer-text": "&copy; 2024 EuroTrans. All rights reserved.",
        "hero-title": "Comfort Travel: Bulgaria <-> Moldova",
        "hero-desc": "Luxury, Wi-Fi and professional service.",
        "hero-btn": "Book a Seat",
        "why-title": "Why Choose Us?",
        "card-1-title": "No Hidden Fees",
        "card-1-desc": "Final price including luggage.",
        "card-2-title": "Comfort",
        "card-2-desc": "Stops at convenient rest areas.",
        "card-3-title": "VIP Travel",
        "card-3-desc": "Travel in style with our new vehicles.",
        "routes-title": "Our Routes",
        "route-1-title": "Line: Bulgaria - Moldova",
        "route-1-path": "Sofia ➔ Ruse ➔ Galati ➔ Chisinau",
        "route-1-info": "Transit via: Romania (Danube Bridge, Bucharest ring, Galati).",
        "route-2-title": "Line: Moldova - Bulgaria",
        "route-2-path": "Chisinau ➔ Galati ➔ Ruse ➔ Sofia",
        "route-2-info": "Return trip via the same route.",
        "schedule-title": "Weekly Schedule",
        "th-day": "Day",
        "th-dest": "Direction",
        "th-time": "Departure Time",
        "th-type": "Vehicle",
        "sched-row-1-day": "Friday",
        "sched-row-1-dest": "Sofia -> Chisinau",
        "sched-row-2-day": "Sunday",
        "sched-row-2-dest": "Chisinau -> Sofia",
        "sched-note": "* Arrival depends on border crossing times.",
        "fleet-title": "Our Fleet",
        "fleet-1-title": "Mercedes-Benz V-Class",
        "fleet-1-desc": "True VIP comfort. Leather seats, individual tables, and climate control for every passenger.",
        "fleet-2-title": "Mercedes Sprinter VIP",
        "fleet-2-desc": "Spacious minibus for small groups with large luggage space and TV.",
        "contact-title": "Contact Us",
        "office-title": "Office",
        "work-hours": "Working Hours",
        "form-title": "Online Booking",
        "lbl-name": "Name:",
        "lbl-phone": "Phone:",
        "lbl-route": "Route:",
        "lbl-date": "Date:",
        "lbl-info": "Info:",
        "btn-send": "Send Request"
    },
    "ru": {
        "nav-home": "Главная",
        "nav-routes": "Маршруты",
        "nav-schedule": "Расписание",
        "nav-fleet": "Автопарк",
        "nav-contact": "Контакты",
        "btn-book": "Забронировать",
        "footer-text": "&copy; 2024 EuroTrans. Все права защищены.",
        "hero-title": "Комфортная поездка: Болгария <-> Молдова",
        "hero-desc": "Люкс, Wi-Fi и профессиональный сервис.",
        "hero-btn": "Забронировать",
        "why-title": "Почему мы?",
        "card-1-title": "Без скрытых такс",
        "card-1-desc": "Окончательная цена с багажом.",
        "card-2-title": "Удобство",
        "card-2-desc": "Остановки в удобных местах.",
        "card-3-title": "VIP Путешествие",
        "card-3-desc": "Путешествуйте стильно на наших новых авто.",
        "routes-title": "Наши Маршруты",
        "route-1-title": "Линия: Болгария - Молдова",
        "route-1-path": "София ➔ Русе ➔ Галац ➔ Кишинев",
        "route-1-info": "Транзит через: Румыния (Дунав мост, Бухарест, Галац).",
        "route-2-title": "Линия: Молдова - Болгария",
        "route-2-path": "Кишинев ➔ Галац ➔ Русе ➔ София",
        "route-2-info": "Обратный рейс по тому же маршруту.",
        "schedule-title": "Расписание",
        "th-day": "День",
        "th-dest": "Направление",
        "th-time": "Время отправления",
        "th-type": "Автомобиль",
        "sched-row-1-day": "Пятница",
        "sched-row-1-dest": "София -> Кишинев",
        "sched-row-2-day": "Воскресенье",
        "sched-row-2-dest": "Кишинев -> София",
        "sched-note": "* Прибытие зависит от границ.",
        "fleet-title": "Наш Автопарк",
        "fleet-1-title": "Mercedes-Benz V-Class",
        "fleet-1-desc": "Настоящий VIP комфорт. Кожаные сиденья, столики и климат-контроль.",
        "fleet-2-title": "Mercedes Sprinter VIP",
        "fleet-2-desc": "Просторный микроавтобус с большим багажником и ТВ.",
        "contact-title": "Контакты",
        "office-title": "Офис",
        "work-hours": "Рабочее время",
        "form-title": "Бронирование",
        "lbl-name": "Имя:",
        "lbl-phone": "Телефон:",
        "lbl-route": "Маршрут:",
        "lbl-date": "Дата:",
        "lbl-info": "Инфо:",
        "btn-send": "Отправить"
    },
    "ua": {
        "nav-home": "Головна",
        "nav-routes": "Маршрути",
        "nav-schedule": "Розклад",
        "nav-fleet": "Автопарк",
        "nav-contact": "Контакти",
        "btn-book": "Забронювати",
        "footer-text": "&copy; 2024 EuroTrans. Всі права захищені.",
        "hero-title": "Комфортна поїздка: Болгарія <-> Молдова",
        "hero-desc": "Люкс, Wi-Fi та професійний сервіс.",
        "hero-btn": "Забронювати",
        "why-title": "Чому ми?",
        "card-1-title": "Без прихованих оплат",
        "card-1-desc": "Кінцева ціна з багажем.",
        "card-2-title": "Зручність",
        "card-2-desc": "Зупинки у зручних місцях.",
        "card-3-title": "VIP Подорож",
        "card-3-desc": "Подорожуйте стильно на наших нових авто.",
        "routes-title": "Наші Маршрути",
        "route-1-title": "Лінія: Болгарія - Молдова",
        "route-1-path": "Софія ➔ Русе ➔ Галац ➔ Кишинів",
        "route-1-info": "Транзит через: Румунія (Дунав міст, Бухарест, Галац).",
        "route-2-title": "Лінія: Молдова - Болгарія",
        "route-2-path": "Кишинів ➔ Галац ➔ Русе ➔ Софія",
        "route-2-info": "Зворотній рейс за тим самим маршрутом.",
        "schedule-title": "Розклад",
        "th-day": "День",
        "th-dest": "Напрямок",
        "th-time": "Час відправлення",
        "th-type": "Автомобіль",
        "sched-row-1-day": "П'ятниця",
        "sched-row-1-dest": "Софія -> Кишинів",
        "sched-row-2-day": "Неділя",
        "sched-row-2-dest": "Кишинів -> Софія",
        "sched-note": "* Прибуття залежить від кордонів.",
        "fleet-title": "Наш Автопарк",
        "fleet-1-title": "Mercedes-Benz V-Class",
        "fleet-1-desc": "Справжній VIP комфорт. Шкіряні сидіння, столики та клімат-контроль.",
        "fleet-2-title": "Mercedes Sprinter VIP",
        "fleet-2-desc": "Просторий мікроавтобус з великим багажником та ТБ.",
        "contact-title": "Контакти",
        "office-title": "Офіс",
        "work-hours": "Робочий час",
        "form-title": "Бронювання",
        "lbl-name": "Ім'я:",
        "lbl-phone": "Телефон:",
        "lbl-route": "Маршрут:",
        "lbl-date": "Дата:",
        "lbl-info": "Інфо:",
        "btn-send": "Надіслати"
    }
};

function changeLanguage(lang) {
    localStorage.setItem('selectedLang', lang);
    const selectedData = translations[lang];

    for (let key in selectedData) {
        let element = document.getElementById(key);
        if (element) {
            if(element.tagName === 'INPUT' && (element.type === 'submit' || element.type === 'button')) {
                element.value = selectedData[key];
            } else {
                element.innerHTML = selectedData[key];
            }
        }
    }
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLang') || 'bg';
    const select = document.querySelector('.lang-select');
    if(select) select.value = savedLang;
    changeLanguage(savedLang);
});